version: '3'
name: medeva
services:
  db:
    image: postgres:latest
    container_name: medeva-db
    environment:
      POSTGRES_DB: "${DB_NAME}"
      POSTGRES_USER: "${DB_USER}"
      POSTGRES_PASSWORD: "${DB_PASSWORD}"
      PGDATA: /data/postgres
    volumes:
      - data:/data/postgres:Z
    ports:
      - ${DB_PORT}:5432
    networks:
      - mynetwork
    restart: unless-stopped

  adminer:
    image: adminer:latest
    container_name: medeva-adminer
    environment:
      ADMINER_DEFAULT_SERVER: db
    ports:
      - 8080:8080
    networks:
      - mynetwork
    restart: unless-stopped

networks:
  mynetwork:

volumes: 
  data:
