version: '3'
name: medeva
services:
  db:
    image: postgres:latest
    container_name: medeva-db
    environment:
      POSTGRES_DB: "${DB_NAME}"
      POSTGRES_USER: "${DB_USER}"
      POSTGRES_PASSWORD: "${DB_PASSWORD}"
      PGDATA: /data/postgres
    volumes:
      - data:/data/postgres:Z
    ports:
      - ${DB_PORT}:5432
    networks:
      - mynetwork
    restart: unless-stopped

  adminer:
    image: adminer:latest
    container_name: medeva-adminer
    environment:
      ADMINER_DEFAULT_SERVER: db
    ports:
      - 8080:8080
    networks:
      - mynetwork
    restart: unless-stopped
  web1:
    restart: on-failure
    build: ./dist
    hostname: https://www.mafiastore.com
    ports:
      - '81:5000'
  nginx:
    image: nginx
    build: ./nginx
    ports:
    - '80:80'
    depends_on:
    - web1
networks:
  mynetwork:

volumes: 
  data:
